import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    domains: [
      "image.zdnet.co.kr",
      "images.unsplash.com",
      "via.placeholder.com",
      "picsum.photos",
      "source.unsplash.com",
      "www.yonhapnewstv.co.kr",
      "img.yna.co.kr",
      "imgnews.pstatic.net",
      "cdn.aitimes.kr",
      "cdn.aitimes.com",
      "www.bloter.net",
      "newsimg.sedaily.com",
      "img.hankyung.com",
      "image.chosun.com",
      "img.hani.co.kr",
      "image.ajunews.com",
      "img.etnews.com",
      "cdn.getnews.co.kr",
      "cdn.digitaltoday.co.kr",
      "www.sisajournal.com",
      "www.sisain.co.kr",
      "www.hankookilbo.com",
      "www.mk.co.kr",
      "biz.chosun.com",
      "www.edaily.co.kr",
      "www.fnnews.com",
      "www.mt.co.kr",
      "www.sedaily.com",
      "www.seoul.co.kr",
      "www.segye.com",
      "www.hankyung.com",
      "www.hani.co.kr",
      "www.joongang.co.kr",
      "www.donga.com",
      "www.chosun.com",
      "news.kbs.co.kr",
      "news.sbs.co.kr",
      "news.jtbc.co.kr",
      "news.joins.com",
      "news.naver.com",
      "news.google.com",
      "news.daum.net",
      "ojsfile.ohmynews.com",
      "img.khan.co.kr",
      "img1.daumcdn.net",
      "blog.outsider.ne.kr",
      "ojsimg.ohmynews.com",
      "newspeppermint.com",
      "image.inews24.com",
    ],
  },
  reactStrictMode: true,
};

export default nextConfig;
